import { StyleSheet } from 'react-native';
import { COLORS, FF, FS, LH } from '../../../../constants';

const PanicSOSAlertStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  sosSection: {
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 32,
    paddingVertical: 32,
    paddingHorizontal: 20,
    backgroundColor: COLORS.LIGHT_GRAY,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: COLORS.BORDER_GREY,
  },
  sosTitle: {
    fontSize: FS.FS24,
    fontFamily: FF[700],
    color: COLORS.ERROR_COLOR,
    marginBottom: 8,
    textAlign: 'center',
    lineHeight: LH.LH30,
  },
  sosSubtitle: {
    fontSize: FS.FS14,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: LH.LH20,
  },
  sosButton: {
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: COLORS.ERROR_COLOR,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.ERROR_COLOR,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 8,
  },
  sosButtonActive: {
    backgroundColor: COLORS.ORANGE_TEXT,
  },
  sosButtonInner: {
    width: '100%',
    height: '100%',
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  sosButtonText: {
    fontSize: FS.FS32,
    fontFamily: FF[800],
    color: COLORS.WHITE,
    letterSpacing: 4,
    lineHeight: LH.LH40,
  },
  cancelButton: {
    marginTop: 20,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: COLORS.WHITE,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
  },
  cancelButtonText: {
    fontSize: FS.FS14,
    fontFamily: FF[600],
    color: COLORS.BLACK_TEXT,
    lineHeight: LH.LH20,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: FS.FS18,
    fontFamily: FF[700],
    color: COLORS.BLACK_TEXT,
    marginBottom: 16,
    lineHeight: LH.LH22,
  },
  quickActionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  quickActionButton: {
    width: '48%',
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.BORDER_GREY,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
  },
  quickActionIcon: {
    fontSize: FS.FS32,
    marginBottom: 8,
  },
  quickActionText: {
    fontSize: FS.FS14,
    fontFamily: FF[600],
    color: COLORS.BLACK_TEXT,
    lineHeight: LH.LH20,
  },
  contactCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    fontSize: FS.FS16,
    fontFamily: FF[600],
    color: COLORS.BLACK_TEXT,
    marginBottom: 4,
    lineHeight: LH.LH20,
  },
  contactPhone: {
    fontSize: FS.FS14,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
    lineHeight: LH.LH18,
  },
  callButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.OCEAN_BLUE_BG,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.OCEAN_BLUE_BORDER,
  },
  callButtonText: {
    fontSize: FS.FS20,
  },
  historyCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  historyType: {
    fontSize: FS.FS16,
    fontFamily: FF[600],
    color: COLORS.BLACK_TEXT,
    lineHeight: LH.LH20,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: COLORS.ERROR_COLOR,
  },
  statusBadgeResolved: {
    backgroundColor: COLORS.GREEN_TEXT,
  },
  statusText: {
    fontSize: FS.FS11,
    fontFamily: FF[600],
    color: COLORS.WHITE,
    lineHeight: LH.LH14,
  },
  historyTimestamp: {
    fontSize: FS.FS12,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
    marginBottom: 4,
    lineHeight: LH.LH16,
  },
  historyResponded: {
    fontSize: FS.FS12,
    fontFamily: FF[400],
    color: COLORS.OCEAN_BLUE_TEXT,
    lineHeight: LH.LH16,
  },
  noticeSection: {
    backgroundColor: COLORS.YELLOW_BG,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.YELLOW_BORDER,
    marginTop: 8,
  },
  noticeTitle: {
    fontSize: FS.FS16,
    fontFamily: FF[700],
    color: COLORS.BLACK_TEXT,
    marginBottom: 8,
    lineHeight: LH.LH20,
  },
  noticeText: {
    fontSize: FS.FS13,
    fontFamily: FF[400],
    color: COLORS.BLACK_TEXT,
    lineHeight: LH.LH18,
  },
  permissionSection: {
    backgroundColor: COLORS.OCEAN_BLUE_BG,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.OCEAN_BLUE_BORDER,
  },
  permissionTitle: {
    fontSize: FS.FS16,
    fontFamily: FF[700],
    color: COLORS.BLACK_TEXT,
    marginBottom: 12,
    lineHeight: LH.LH20,
  },
  permissionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  permissionLabel: {
    fontSize: FS.FS14,
    fontFamily: FF[600],
    color: COLORS.BLACK_TEXT,
    marginRight: 8,
    lineHeight: LH.LH20,
  },
  permissionBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    marginRight: 8,
  },
  permissionBadgeGranted: {
    backgroundColor: COLORS.GREEN_TEXT,
  },
  permissionBadgeDenied: {
    backgroundColor: COLORS.ERROR_COLOR,
  },
  permissionText: {
    fontSize: FS.FS12,
    fontFamily: FF[600],
    color: COLORS.WHITE,
    lineHeight: LH.LH16,
  },
  permissionButton: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: COLORS.OCEAN_BLUE_TEXT,
    marginLeft: 'auto',
  },
  permissionButtonText: {
    fontSize: FS.FS12,
    fontFamily: FF[600],
    color: COLORS.WHITE,
    lineHeight: LH.LH16,
  },
  locationInfo: {
    fontSize: FS.FS12,
    fontFamily: FF[400],
    color: COLORS.GREEN_TEXT,
    marginTop: 8,
    lineHeight: LH.LH16,
  },
});

export default PanicSOSAlertStyles;

