import { StyleSheet } from 'react-native';
import { COLORS, FF, FS, LH } from '../../../constants';

export const amenitiesBookingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999, // optional
  },
  contentWrapper: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 100,
  },
  amenityInfoCard: {
    backgroundColor: COLORS.LIGHT_BLUE,
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: COLORS.BLUE_BORDER,
  },
  amenityName: {
    fontSize: FS.FS20,
    fontFamily: FF[600],
    color: COLORS.BLACK_TEXT,
    lineHeight: LH.LH27,
    marginBottom: 4,
  },
  amenityDescription: {
    fontSize: FS.FS14,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
    lineHeight: LH.LH20,
  },
  sectionTitle: {
    fontSize: FS.FS16,
    fontFamily: FF[600],
    color: COLORS.BLACK_TEXT,
    lineHeight: LH.LH24,
    marginBottom: 12,
  },
  selectedDatesContainer: {
    marginTop: 24,
    backgroundColor: COLORS.LIGHT_GREEN,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.LIGHT_BORDER_GREEN,
  },
  selectedDatesTitle: {
    fontSize: FS.FS16,
    fontFamily: FF[600],
    color: COLORS.GREEN_TEXT,
    lineHeight: LH.LH24,
    marginBottom: 8,
  },
  selectedDate: {
    fontSize: FS.FS14,
    fontFamily: FF[400],
    color: COLORS.GREEN_TEXT,
    lineHeight: LH.LH20,
    marginTop: 4,
  },
  submitButtonWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.BORDER_GREY,
  },
  timeSection: {
    marginTop: 24,
  },
  timeInput: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timeLabel: {
    fontSize: FS.FS14,
    fontFamily: FF[500],
    color: COLORS.GREY_TEXT,
  },
  timeValue: {
    fontSize: FS.FS16,
    fontFamily: FF[600],
    color: COLORS.BLACK_TEXT,
  },
  amountCard: {
    backgroundColor: COLORS.LIGHT_GREEN || '#F0FDF4',
    borderRadius: 12,
    padding: 20,
    marginTop: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.LIGHT_BORDER_GREEN || '#86EFAC',
  },
  amountLabel: {
    fontSize: FS.FS14,
    fontFamily: FF[500],
    color: COLORS.GREY_TEXT,
    marginBottom: 8,
  },
  amountValue: {
    fontSize: FS.FS32,
    fontFamily: FF[700],
    color: COLORS.GREEN_TEXT || '#16A34A',
  },
  amountSubtext: {
    fontSize: FS.FS12,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
    marginTop: 4,
  },
  remarksSection: {
    marginTop: 24,
  },
  pickerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  iosTimePicker: {
    width: '100%',
    height: 200,
  },
  paymentContainer: {
    paddingVertical: 10,
  },
  paymentInstruction: {
    fontSize: FS.FS14,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
    textAlign: 'center',
    marginBottom: 20,
  },
  qrCodeWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
  },
  qrCodeImage: {
    width: 200,
    height: 200,
  },
  qrCodePlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.LIGHT_GREY || '#F5F5F5',
    borderRadius: 12,
    padding: 40,
    marginBottom: 20,
    height: 200,
  },
  qrCodePlaceholderText: {
    fontSize: FS.FS14,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
  },
  paymentDetails: {
    backgroundColor: COLORS.LIGHT_BLUE || '#F0F9FF',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.BLUE_BORDER || '#BFDBFE',
  },
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  paymentLabel: {
    fontSize: FS.FS14,
    fontFamily: FF[500],
    color: COLORS.GREY_TEXT,
  },
  paymentValue: {
    fontSize: FS.FS14,
    fontFamily: FF[600],
    color: COLORS.BLACK_TEXT,
    maxWidth: '60%',
    textAlign: 'right',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: COLORS.BORDER_GREY || '#E5E7EB',
    paddingTop: 12,
    marginTop: 4,
    marginBottom: 0,
  },
  totalLabel: {
    fontSize: FS.FS16,
    fontFamily: FF[600],
    color: COLORS.BLACK_TEXT,
  },
  totalValue: {
    fontSize: FS.FS20,
    fontFamily: FF[700],
    color: COLORS.GREEN_TEXT || '#16A34A',
  },
});
