export const defaultIcon = {
  ['search-ic']: require('./resources/search-ic.svg').default,
  ['radio-ic']: require('./resources/radio-ic.svg').default,
  ['radio-sele-ic']: require('./resources/radio-sele-ic.svg').default,
  ['amenities-ic']: require('./resources/amenities-ic.svg').default,
  ['helpdesk-ic']: require('./resources/helpdesk-ic.svg').default,
  ['security-ic']: require('./resources/security-ic.svg').default,
  ['sos-ic']: require('./resources/sos-ic.svg').default,
  ['report-ic']: require('./resources/report-ic.svg').default,
  ['dashboard-ic']: require('./resources/dashboard-ic.svg').default,
  ['unit-management-ic']: require('./resources/unit-management-ic.svg').default,
  ['lost-found-ic']: require('./resources/lost-found-ic.svg').default,
  ['notice-ic']: require('./resources/notice-ic.svg').default,
  ['parking-ic']: require('./resources/parking-ic.svg').default,
  ['visitor-entry-ic']: require('./resources/visitor-entry-ic.svg').default,
  ['complaints-ic']: require('./resources/helpdesk-ic.svg').default, // Using helpdesk icon for complaints
  // Emergency SOS Icons
  ['medical-emergency-ic']: require('./resources/medical-emergency-ic.svg').default,
  ['fire-emergency-ic']: require('./resources/fire-emergency-ic.svg').default,
  ['theft-security-ic']: require('./resources/theft-security-ic.svg').default,
  ['ambulance-ic']: require('./resources/ambulance-ic.svg').default,
  ['fire-flame-ic']: require('./resources/fire-flame-ic.svg').default,
  ['police-shield-ic']: require('./resources/police-shield-ic.svg').default,
  ['arrow-right-ic']: require('./resources/arrow-right-ic.svg').default,
  ['parking']: require('./resources/parking.svg').default,
  ['lost-found']: require('./resources/lost-found.svg').default,
  ['notice']: require('./resources/notice.svg').default,
  ['complain']: require('./resources/complain.svg').default,
  ['myunit']: require('./resources/myunit.svg').default,
  ['amenities']: require('./resources/amenities.svg').default,
};
