import { StyleSheet } from 'react-native';
import { COLORS, FF, FS, LH, SPACING, BORDER_RADIUS } from '../../../constants';

const SettingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  contentWrapper: {
    flex: 1,
    alignItems: 'center',
    paddingTop: SPACING.XXL,
    paddingHorizontal: 0,
  },
  card: {
    width: '90%',
    borderRadius: BORDER_RADIUS.MD,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
    alignSelf: 'center',
    backgroundColor: COLORS.WHITE,
  },
  profileCard: {
    width: '90%',
    backgroundColor: COLORS.WHITE,
    borderRadius: BORDER_RADIUS.MD,
    padding: SPACING.XL,
    marginBottom: SPACING.XL,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
    alignSelf: 'center',
  },
  cardTitle: {
    fontFamily: FF[600],
    fontSize: FS.FS16,
    color: COLORS.BLACK,
    marginBottom: SPACING.MD,
    lineHeight: LH.LH20,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileAvatarContainer: {
    position: 'relative',
    marginRight: SPACING.LG,
  },
  profileAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.BLACK,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verifiedBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: SPACING.XL,
    height: SPACING.XL,
    borderRadius: SPACING.XL / 2,
    backgroundColor: COLORS.BLACK,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: COLORS.WHITE,
  },
  verifiedBadgeText: {
    color: COLORS.WHITE,
    fontSize: FS.FS12,
    fontFamily: FF[700],
  },
  profileAvatarText: {
    color: COLORS.WHITE,
    fontFamily: FF[700],
    fontSize: FS.FS20,
    lineHeight: LH.LH24,
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontFamily: FF[600],
    fontSize: FS.FS18,
    color: COLORS.BLACK,
    marginBottom: SPACING.SM,
    lineHeight: LH.LH22,
  },
  phoneContainer: {
    // borderWidth: 1,
    // borderColor: '#E3F2FD',
    // borderRadius: 8,
    // paddingHorizontal: 12,
    // paddingVertical: 6,
    // alignSelf: 'flex-start',
  },
  phoneText: {
    fontFamily: FF[400],
    fontSize: FS.FS14,
    color: COLORS.GREY_TEXT,
    lineHeight: LH.LH18,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.GREY_TEXT,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: SPACING.LG,
  },
  avatarText: {
    color: COLORS.WHITE,
    fontFamily: FF[700],
    fontSize: FS.FS20,
    lineHeight: LH.LH24,
  },
  info: {
    flex: 1,
  },
  name: {
    fontFamily: FF[400],
    fontSize: FS.FS24,
    color: COLORS.BLACK,
    lineHeight: LH.LH30,
  },
  rid: {
    fontFamily: FF[400],
    fontSize: FS.FS18,
    color: COLORS.GREY_TEXT,
    marginTop: SPACING.SM,
    lineHeight: LH.LH22,
  },
  section: {
    width: '90%',
    alignSelf: 'center',
    marginBottom: 16,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.WHITE,
    borderRadius: BORDER_RADIUS.MD,
    paddingVertical: SPACING.LG,
    paddingHorizontal: SPACING.LG,
    marginBottom: SPACING.MD,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
  },
  listItemDisabled: {
    opacity: 0.5,
  },
  icon: {
    marginRight: SPACING.LG,
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listText: {
    fontFamily: FF[500],
    fontSize: FS.FS15,
    color: COLORS.BLACK,
    lineHeight: LH.LH20,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.WHITE,
    borderRadius: BORDER_RADIUS.MD,
    paddingVertical: SPACING.LG,
    paddingHorizontal: SPACING.LG,
    marginBottom: SPACING.MD,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuIcon: {
    fontSize: FS.FS20,
    marginRight: SPACING.MD,
  },
  menuText: {
    fontFamily: FF[500],
    fontSize: FS.FS15,
    color: COLORS.BLACK,
    lineHeight: LH.LH20,
  },
  chevron: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    tintColor: COLORS.GREY_TEXT,
    transform: [{ rotate: '180deg' }],
  },
  logoutItem: {
    alignItems: 'center',
    backgroundColor: COLORS.WHITE,
    borderRadius: BORDER_RADIUS.MD,
    paddingVertical: SPACING.LG,
    paddingHorizontal: SPACING.LG,
    marginBottom: SPACING.MD,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
  },
  deleteItem: {
    alignItems: 'center',
    backgroundColor: COLORS.WHITE,
    borderRadius: BORDER_RADIUS.MD,
    paddingVertical: SPACING.LG,
    paddingHorizontal: SPACING.LG,
    marginBottom: SPACING.XXL,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
  },
  logoutIcon: {
    marginRight: SPACING.LG,
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutText: {
    fontFamily: FF[500],
    fontSize: FS.FS15,
    color: COLORS.ERROR_COLOR,
    lineHeight: LH.LH20,
  },
  deleteText: {
    fontFamily: FF[500],
    fontSize: FS.FS15,
    color: COLORS.ERROR_COLOR,
    lineHeight: LH.LH20,
  },
  spacer: {
    height: SPACING.XL,
  },
  actionSection: {
    width: '90%',
    alignSelf: 'center',
    marginTop: SPACING.XL,
  },
  actionButton: {
    alignItems: 'center',
    backgroundColor: COLORS.WHITE,
    borderRadius: BORDER_RADIUS.MD,
    paddingVertical: SPACING.XXL,
    paddingHorizontal: SPACING.XL,
    marginBottom: SPACING.LG,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
  },
  actionButtonText: {
    fontFamily: FF[500],
    fontSize: FS.FS16,
    color: COLORS.BLACK,
    lineHeight: LH.LH20,
  },
  versionContainer: {
    paddingVertical: SPACING.XXXL,
    alignItems: 'center',
  },
  versionText: {
    fontFamily: FF[400],
    fontSize: FS.FS13,
    color: COLORS.GREY_TEXT,
    lineHeight: LH.LH16,
  },
  profileCardTouch: {
    paddingVertical: SPACING.XL,
    paddingHorizontal: SPACING.XL,
  },
  profileEmail: {
    fontSize: FS.FS13,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
    marginTop: SPACING.XS,
    lineHeight: LH.LH16,
  },
  unitInfoCard: {
    marginTop: SPACING.LG,
    backgroundColor: COLORS.WHITE,
    padding: SPACING.LG,
    borderRadius: BORDER_RADIUS.MD,
    width: '90%',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
    marginBottom: SPACING.LG,
  },
  unitLabel: {
    fontSize: FS.FS12,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
    marginBottom: SPACING.XS,
    lineHeight: LH.LH16,
  },
  unitText: {
    fontSize: FS.FS18,
    fontFamily: FF[600],
    color: COLORS.BLACK,
    marginBottom: SPACING.XS,
    lineHeight: LH.LH22,
  },
  badgeRow: {
    flexDirection: 'row',
    marginTop: SPACING.SM,
  },
  residentBadge: {
    paddingHorizontal: SPACING.SM,
    paddingVertical: SPACING.XS,
    borderRadius: BORDER_RADIUS.MD,
    marginRight: SPACING.SM,
  },
  badgeText: {
    color: COLORS.WHITE,
    fontSize: FS.FS11,
    fontFamily: FF[600],
    lineHeight: LH.LH14,
  },
  memberSinceText: {
    fontSize: FS.FS12,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
    alignSelf: 'center',
    lineHeight: LH.LH16,
  },
  scrollView: {
    flex: 1,
    width: '100%',
  },
  sectionMarginTop: {
    marginTop: SPACING.LG,
  },
  ownerBadge: {
    backgroundColor: COLORS.GREEN_TEXT,
  },
  tenantBadge: {
    backgroundColor: COLORS.OCEAN_BLUE_TEXT,
  },
});

export default SettingStyles;
