import { StyleSheet } from 'react-native';
import { COLORS, FF, FS, LH } from '../../../constants';

const SmartSocietyStyles = StyleSheet.create({
  container: {
    flex: 1,
    // backgroundColor: COLORS.LIGHT_GRAY,
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  headerSection: {
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER_GREY,
  },
  headerImageContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.LIGHT_BLUE,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
  },
  headerImage: {
    width: 56,
    height: 56,
    resizeMode: 'contain',
  },
  headerTitle: {
    fontSize: FS.FS24,
    fontFamily: FF[700],
    color: COLORS.BLACK_TEXT,
    marginBottom: 6,
    textAlign: 'center',
    letterSpacing: 0.3,
    lineHeight: LH.LH30,
  },
  headerSubtitle: {
    fontSize: FS.FS13,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
    textAlign: 'center',
    paddingHorizontal: 20,
    lineHeight: LH.LH18,
    marginBottom: 16,
  },
  roleBadgeContainer: {
    marginTop: 12,
    alignItems: 'center',
  },
  roleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
  },
  roleBadgeIcon: {
    fontSize: FS.FS18,
    marginRight: 8,
  },
  roleBadgeText: {
    fontSize: FS.FS13,
    fontFamily: FF[600],
    color: COLORS.BLACK_TEXT,
    lineHeight: LH.LH18,
  },
  headerStatsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  statItem: {
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  statNumber: {
    fontSize: FS.FS20,
    fontFamily: FF[700],
    color: COLORS.OCEAN_BLUE_TEXT,
    marginBottom: 2,
    lineHeight: LH.LH24,
  },
  statLabel: {
    fontSize: FS.FS11,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
    lineHeight: LH.LH14,
  },
  statDivider: {
    width: 1,
    height: 24,
    backgroundColor: COLORS.BORDER_GREY,
  },
  featuresSection: {
    marginTop: 10,
  },
  sectionTitle: {
    fontSize: FS.FS20,
    fontFamily: FF[600],
    color: COLORS.BLACK_TEXT,
    marginBottom: 16,
    lineHeight: LH.LH24,
  },
  categorySection: {
    marginTop: 24,
    marginBottom: 8,
  },
  categoryHeaderContainer: {
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 12,
    borderWidth: 1,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  categoryHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  categoryIcon: {
    fontSize: FS.FS20,
    marginRight: 8,
  },
  categoryTitle: {
    fontSize: FS.FS16,
    fontFamily: FF[600],
    flex: 1,
    lineHeight: LH.LH20,
  },
  categoryBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 6,
  },
  categoryBadgeText: {
    fontSize: FS.FS11,
    fontFamily: FF[700],
    color: COLORS.WHITE,
    lineHeight: LH.LH14,
  },
  featuresList: {
    paddingBottom: 10,
  },
  row: {
    justifyContent: 'space-between',
  },
  featureCard: {
    width: '48%',
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.BORDER_GREY,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 12,
    position: 'relative',
    minHeight: 130,
  },
  featureIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  featureIcon: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },
  featureContent: {
    flex: 1,
    marginBottom: 6,
  },
  featureTitle: {
    fontSize: FS.FS14,
    fontFamily: FF[600],
    color: COLORS.BLACK_TEXT,
    marginBottom: 6,
    lineHeight: LH.LH18,
  },
  featureDescription: {
    fontSize: FS.FS10,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
    lineHeight: LH.LH14,
  },
  arrowContainer: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrowText: {
    fontSize: FS.FS16,
    fontFamily: FF[600],
    lineHeight: LH.LH20,
  },
  emptyStateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 20,
  },
  emptyStateText: {
    fontSize: FS.FS16,
    fontFamily: FF[400],
    color: COLORS.GREY_TEXT,
    textAlign: 'center',
    lineHeight: LH.LH24,
  },
});

export default SmartSocietyStyles;
