import { StyleSheet } from "react-native";
import { COLORS, FF, FS, LH, SPACING, BORDER_RADIUS } from "../../../constants";

const ProjectStyles = StyleSheet.create({
    container: {
      backgroundColor: COLORS.WHITE,
      paddingHorizontal: SPACING.XL,
    },
    card: {
      backgroundColor: COLORS.WHITE,
      borderRadius: BORDER_RADIUS.MD,
      marginBottom: SPACING.LG,
      width: '100%',
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: COLORS.BORDER_GREY,
    },
    imageContainer: {
      position: 'relative',
      height: 203,
    },
    image: {
      width: '100%',
      height: '100%',
      borderTopRightRadius: BORDER_RADIUS.MD,
      borderTopLeftRadius: BORDER_RADIUS.MD,
      overflow: 'hidden',
      resizeMode: 'cover',
    },
    statusTag: {
      position: 'absolute',
      top: SPACING.SM,
      right: SPACING.SM,
      paddingHorizontal: SPACING.SM,
      paddingVertical: SPACING.SM,
      borderRadius: BORDER_RADIUS.SM,
      backgroundColor: COLORS.WHITE,
    },
    statusText: {
      fontSize: FS.FS12,
      fontFamily: FF[400],
      color: COLORS.BLACK,
    },
    priceBadge: {
      position: 'absolute',
      bottom: SPACING.SM,
      left: SPACING.SM,
      backgroundColor: 'rgba(0,0,0,0.9)',
      paddingHorizontal: SPACING.SM,
      paddingVertical: SPACING.SM,
      borderRadius: BORDER_RADIUS.MD,
      zIndex: 1,
    },
    priceBadgeText: {
      fontSize: FS.FS12,
      fontFamily: FF[600],
      color: COLORS.WHITE,
      letterSpacing: 0.5,
    },
    typeBadge: {
      position: 'absolute',
      top: SPACING.SM,
      left: SPACING.SM,
      backgroundColor: 'rgba(255,255,255,0.95)',
      paddingHorizontal: SPACING.SM,
      paddingVertical: SPACING.XS,
      borderRadius: BORDER_RADIUS.SM,
    },
    typeBadgeText: {
      fontSize: FS.FS10,
      fontFamily: FF[600],
      color: COLORS.BLACK_TEXT,
    },
    imageCountBadge: {
      position: 'absolute',
      bottom: SPACING.SM,
      right: SPACING.SM,
      backgroundColor: 'rgba(0,0,0,0.7)',
      paddingHorizontal: SPACING.SM,
      paddingVertical: SPACING.XS,
      borderRadius: BORDER_RADIUS.SM,
    },
    imageCountText: {
      fontSize: FS.FS10,
      fontFamily: FF[600],
      color: COLORS.WHITE,
    },
    loadingContainer: {
      paddingVertical: SPACING.XL,
      alignItems: 'center',
      justifyContent: 'center',
    },
    loadingText: {
      color: COLORS.GREY_TEXT,
      fontSize: FS.FS14,
      fontFamily: FF[500],
    },
    content: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    headerRow: {
      marginBottom: SPACING.SM,
    },
    title: {
      fontSize: FS.FS18,
      fontFamily: FF[500],
      color: COLORS.BLACK,
      lineHeight: LH.LH22,
    },
    locationContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    // locationIcon: {
    //   fontSize: 12,
    //   marginRight: 4,
    // },
    location: {
      fontSize: FS.FS16,
      color: COLORS.GREY_TEXT,
      fontFamily: FF[400],
    },
    description: {
      fontSize: FS.FS16,
      color: COLORS.GREY_TEXT,
      fontFamily: FF[400],
      lineHeight: LH.LH24,
      marginTop: SPACING.LG,
    },
    detailsRow: {
      flexDirection: 'row',
      gap: SPACING.SM,
    },
    detailItem: {},
    detailLabel: {
      fontSize: FS.FS10,
      color: COLORS.GREY_TEXT,
      fontFamily: FF[600],
      marginBottom: 2,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    detailValue: {
      fontSize: FS.FS12,
      color: COLORS.BLACK_TEXT,
      fontFamily: FF[600],
    },
    featuresSection: {
      marginBottom: SPACING.SM,
    },
    featureGroup: {
      marginBottom: SPACING.SM,
    },
    featureLabel: {
      fontSize: FS.FS10,
      color: COLORS.GREY_TEXT,
      fontFamily: FF[600],
      marginBottom: SPACING.XS,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    featureTags: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: SPACING.SM,
    },
    connectivityTag: {
      backgroundColor: COLORS.BLUE_BG,
      paddingHorizontal: SPACING.SM,
      paddingVertical: SPACING.XS,
      borderRadius: BORDER_RADIUS.SM,
    },
    connectivityText: {
      fontSize: FS.FS10,
      color: COLORS.BLUE_TEXT,
      fontFamily: FF[500],
    },
    amenityTag: {
      backgroundColor: COLORS.LIGHT_GREEN,
      paddingHorizontal: SPACING.SM,
      paddingVertical: SPACING.XS,
      borderRadius: BORDER_RADIUS.SM,
    },
    amenityText: {
      fontSize: FS.FS10,
      color: COLORS.GREEN_TEXT,
      fontFamily: FF[500],
    },
    greenFeaturesSection: {
      marginBottom: SPACING.SM,
    },
    greenFeatureTag: {
      backgroundColor: COLORS.ORANGE_BG,
      paddingHorizontal: SPACING.SM,
      paddingVertical: SPACING.XS,
      borderRadius: BORDER_RADIUS.SM,
    },
    greenFeatureText: {
      fontSize: FS.FS10,
      color: COLORS.ORANGE_TEXT,
      fontFamily: FF[500],
    },
    bottomRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: SPACING.SM,
    },
    leadButton: {
      backgroundColor: COLORS.BLACK,
      paddingVertical: SPACING.SM,
      paddingHorizontal: SPACING.SM,
      borderRadius: BORDER_RADIUS.XL,
      alignItems: 'center',
      justifyContent: 'center',
      width: 40,
      height: 40,
    },
    leadButtonText: {
      fontSize: FS.FS16,
      color: COLORS.WHITE,
    },
    shareButton: {
      backgroundColor: COLORS.BLACK,
      paddingVertical: SPACING.LG,
      paddingHorizontal: SPACING.XL,
      borderRadius: BORDER_RADIUS.SM,
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
    },
    shareButtonText: {
      fontSize: FS.FS16,
      color: COLORS.WHITE,
      fontFamily: FF[500],
    },
    // Share Modal Styles
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    shareModalContent: {
      backgroundColor: COLORS.WHITE,
      borderRadius: BORDER_RADIUS.XL,
      width: '90%',
      maxHeight: '70%',
      elevation: 5,
      shadowColor: COLORS.BLACK,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      paddingBottom: SPACING.LG,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: SPACING.LG,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.BORDER_GREY,
    },
    modalTitle: {
      fontSize: FS.FS18,
      fontFamily: FF[600],
      color: COLORS.BLACK_TEXT,
    },
    closeButton: {
      padding: SPACING.XS,
    },
    closeButtonText: {
      fontSize: FS.FS20,
      color: COLORS.GREY_TEXT,
      fontFamily: FF[600],
    },
    shareOptionsContainer: {
      padding: SPACING.XL,
    },
    shareOptionsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    shareOptionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '48%',
      marginBottom: SPACING.XL,
    },
    shareOptionLabel: {
      fontSize: FS.FS16,
      fontFamily: FF[400],
      color: COLORS.BLACK,
      marginLeft: SPACING.MD,
      flex: 1,
    },
    shareOptionValue: {
      fontSize: FS.FS14,
      color: COLORS.GREY_TEXT,
      flex: 1,
      flexWrap: 'wrap',
    },
    shareOptionImage: {
      width: 48,
      height: 48,
      borderRadius: BORDER_RADIUS.SM,
      marginLeft: SPACING.SM,
    },
    checkbox: {
      width: 20,
      height: 20,
      borderRadius: BORDER_RADIUS.XS,
      borderWidth: 1,
      borderColor: COLORS.BORDER_GREY,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: COLORS.WHITE,
    },
    checkboxChecked: {
      backgroundColor: COLORS.BLACK,
      borderColor: COLORS.BLACK,
    },
    checkboxText: {
      color: COLORS.WHITE,
      fontSize: FS.FS12,
      fontFamily: FF[600],
    },
    modalFooter: {
      alignItems: 'center',
      alignSelf: 'center',
    },
  });

  export default ProjectStyles;